Add Context interfaces
honeycombio/startstop pull request #1
Opened 2019-10-15 20:00 UTC by tredman

It would be nice to instrument the start/stop process with tracing. To do that, we need to feed a `Context` object down from the start to all of the objects being started or stopped. Those objects can be responsible for adding spans if they desire.

This adds `StartContext` and `StopContext`, which work with `ContextStarter` and `ContextStopper` interfaces as well as the original `Starter` and `Stopper` interfaces. If the `Context*` interfaces don't exist, the original interfaces are called instead. Otherwise, the `Context*` interfaces are preferred.

Note I added tests and ran them locally, but nothing runs these in CI right now

2019-10-15 21:37 UTC, ianwilkes reviewed
I support this endeavor, but I don't see any value in continuing the Start/Stop, Open/Close duality. I would just add StartContext and StopContext, and label the existing Starter,Stopper,Opener,Closer interfaces all as deprecated.

2019-10-15 21:37 UTC, ianwilkes commented on startstop.go
> +				if log != nil {
If you keep this, probably want `ctxUsed = true` here.

2019-10-15 22:36 UTC, tredman commented
> I support this endeavor, but I don't see any value in continuing the Start/Stop, Open/Close duality. I would just add StartContext and StopContext, and label the existing Starter,Stopper,Opener,Closer interfaces all as deprecated.

I was mostly thinking it would make it easier on us to convert all of our `Starter` implementations in our codebase, but maybe that's not that much work.

2019-10-15 22:40 UTC, ianwilkes commented
We have a small handful of Open/Close and I don't know why. This is a great opportunity to be rid of them.

2019-10-16 17:47 UTC, tredman commented
There's a boat load of tests that should probably be refactored to use the new interfaces to be 'correct' but this code is simple enough and not changed frequently enough to make it worthwhile right now.

2019-10-18 18:02 UTC, ianwilkes requested changes
Splitting Start/StartContext means that in a blended environment, you'll need to call Start() and then StartContext(), starting services in the wrong order. Same for stopping.

So *Context should either handle the deprecated interfaces, or you should remove them entirely. I forked startstop recently so I doubt anyone external is using it; a breaking change is fine if you're willing to do the codemod to fix everything.

2019-10-18 18:04 UTC, tredman commented
Ah, yeah I'd planned to convert everything and avoid the blended environment. Suppose it's easier to find and fix everything if the `Starter` interfaces are completely gone

2019-10-18 19:14 UTC, ianwilkes reviewed
So now that we've come this far, is there actually a good reason to rename the methods to *Context?

2019-10-18 20:42 UTC, ianwilkes approved these changes

2019-10-18 22:22 UTC, merged